# Header
menu:
  Digital Strategy: digital-strategy
  Digital Ads: digital-ads
  Email Marketing: email-marketing
  Digital Marketplaces: digital-marketplaces

img_path: /templates/laom/images/

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: 
twitter:
google_plus:
fb_admins:
fb_app_id:
